### PR TITLE
47 general bugfixes and jwt with role check in endpoints

### LINKED ISSUE #47: General bugfixes and jwt with role check in endpoints
## Work to be done in this issue:

 - I need you to add checks for jwt existence as Authorization header, and add role check in any method needed in all endpoints needed in dev, and use mock jwt is their tests.
 
 - Check all create - update endpoints, we have still the getId() problem 
 
- There is a bug in /room/update endpoint - when i tested by giving the year 2027 in pre set dates, the response was that, the room was vacant between those dates, but it shouldnt be (before using that year, i did an update by using the 2017 year, the first time it went though without an error)

- /rooms/create check extensively for all properties in postman and in h2 db -> add to tests so that we can be rest assured that the properties do not have any value from the wrong getter.

Thanks in advance!

### PR DESCRIPTION
**Pull request by georgepoul**
closes #47 @DimK10

### CODE REVIEW

File: src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java [hunk 1]
```diff
@@ -38,8 +38,15 @@ public HotelController(HotelService hotelService, UserService userService) {
      * @return the saved hotel for confirmation
      */
     @PostMapping("/api/hotel/create")
-    public HotelDTO addHotel(@RequestBody HotelDTO hotelDTO) throws ApiRequestException {
-        return service.saveHotelDTO(hotelDTO);
+    @PreAuthorize("hasAuthority('ADMIN')")
+    public HotelDTO addHotel(@RequestHeader(name = "Authorization") String token, @RequestBody HotelDTO hotelDTO) throws ApiRequestException {
+
+        if (Objects.equals(userService.getUserFromToken(token).getId(), hotelDTO.getOwner())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java:44]: There needs to be a null check for userService.getUserFromToken(token), or wrap it in an nullable optional and check if present. If the token is malformed, of for some reason the user cannot be found in db, this will produce NullPointerException.

This can be dealt with a try catch block using Exception in catch, since thise two conditions definetely show that this resource should not axecute a save either way

File: src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java [hunk 2]
```diff
@@ -48,20 +55,32 @@ public HotelDTO addHotel(@RequestBody HotelDTO hotelDTO) throws ApiRequestExcept
      * @return the list of hotels that where saved
      */
     @PostMapping("/api/hotels/create")
-    public List<HotelDTO> addHotels(@RequestBody List<HotelDTO> hotelsDTO) {
+    @PreAuthorize("hasAuthority('ADMIN')")
+    public List<HotelDTO> addHotels(@RequestHeader(name = "Authorization") String token, @RequestBody List<HotelDTO> hotelsDTO) {
 
-        return service.saveHotels(hotelsDTO);
+        if (Objects.equals(hotelsDTO.get(0).getOwner(), userService.getUserFromToken(token).getId())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java]: This should check for each individual hotel owner - an attacker could try to impersonate for the first one only, and not for the rest of the hotels. 

You can user the forEach, with lamda functions.

File: src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java [hunk 3]
```diff
@@ -48,20 +55,32 @@ public HotelDTO addHotel(@RequestBody HotelDTO hotelDTO) throws ApiRequestExcept
...
      * counts all the hotels in the database for a specific user id
      * @return the number of hotels that exists in the database
      */
     @GetMapping("/api/hotels/quantity/{userId}")
-    public int countHotels(@PathVariable Long userId) {
+    @PreAuthorize("hasAuthority('ADMIN')")
+    public int countHotels(@RequestHeader(name = "Authorization") String token, @PathVariable Long userId) {
 
-        return service.countHotels(userId);
+        if (Objects.equals(userId, userService.getUserFromToken(token).getId())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java:87]: Please check or hnadle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java [hunk 4]
```diff
@@ -70,17 +89,24 @@ public int countHotels(@PathVariable Long userId) {
...
             @PathVariable Integer pageSize,
             @PathVariable String sortBy,
             @PathVariable Long userId)
             throws ApiRequestException {
 
-        List<HotelDTO> hotelDTOS = service.getHotels(pageNo, pageSize, sortBy, userId);
+        if (Objects.equals(userId, userService.getUserFromToken(token).getId())) {
 
-        return new ResponseEntity<List<HotelDTO>>(hotelDTOS, new HttpHeaders(), HttpStatus.OK);
+            List<HotelDTO> hotelDTOS = service.getHotels(pageNo, pageSize, sortBy, userId);
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java:115]: Please check for NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java [hunk 5]
```diff
@@ -91,7 +117,7 @@ public ResponseEntity<List<HotelDTO>> findAllRooms(
      */
     @GetMapping("/api/hotelId/{id}")
     @PreAuthorize("hasAuthority('ADMIN')")
-    public HotelDTO findHotelById(@RequestHeader(name="Authorization") String token, @PathVariable Long id) throws ApiRequestException {
+    public HotelDTO findHotelById(@RequestHeader(name = "Authorization") String token, @PathVariable Long id) throws ApiRequestException {
 
         User user = userService.getUserFromToken(token);
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java:133]: Jokes on me i guess: I should also handle NullPointerException, or check with if

File: src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java [hunk 6]
```diff
@@ -117,9 +143,15 @@ public HotelDTO findHotelByName(@PathVariable String name) throws ApiRequestExce
      * @throws ApiRequestException if the hotel does not exist
      */
     @PutMapping("/api/hotel/update")
-    public HotelDTO updateHotel(@RequestBody HotelDTO hotelDTO) throws ApiRequestException {
+    @PreAuthorize("hasAuthority('ADMIN')")
+    public HotelDTO updateHotel(@RequestHeader(name = "Authorization") String token, @RequestBody HotelDTO hotelDTO) throws ApiRequestException {
 
-        return service.updateHotel(hotelDTO);
+        if (Objects.equals(hotelDTO.getOwner(), userService.getUserFromToken(token).getId())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java:160]: Please check or hnadle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java [hunk 7]
```diff
@@ -131,12 +163,19 @@ public HotelDTO updateHotel(@RequestBody HotelDTO hotelDTO) throws ApiRequestExc
...
-    ResponseEntity<String> enableHotel(@PathVariable Long id) throws ApiRequestException {
+    @PreAuthorize("hasAuthority('ADMIN')")
+    ResponseEntity<String> enableHotel(@RequestHeader(name = "Authorization") String token, @PathVariable Long id) throws ApiRequestException {
+
+        HotelDTO hotelOptional = service.getHotelById(id);
 
-        service.enableHotel(id);
-        return ResponseEntity.status(HttpStatus.OK)
-                .body("Hotel with id " + id + " was successfully activated");
+        if (Objects.equals(hotelOptional.getOwner(), userService.getUserFromToken(token).getId())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java:182]: Please check or hnadle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java [hunk 8]
```diff
@@ -147,12 +186,20 @@ ResponseEntity<String> enableHotel(@PathVariable Long id) throws ApiRequestExcep
...
-    ResponseEntity<String> disableHotel(@PathVariable Long id) throws ApiRequestException {
+    @PreAuthorize("hasAuthority('ADMIN')")
+    ResponseEntity<String> disableHotel(@RequestHeader(name = "Authorization") String token, @PathVariable Long id) throws ApiRequestException {
+
+        HotelDTO hotelOptional = service.getHotelById(id);
 
-        service.disableHotel(id);
-        return ResponseEntity.status(HttpStatus.OK)
-                .body("Hotel with id " + id + " was successfully deactivated");
+        if (Objects.equals(hotelOptional.getOwner(), userService.getUserFromToken(token).getId())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java:205]: Please check or hnadle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java [hunk 9]
```diff
@@ -163,9 +210,18 @@ ResponseEntity<String> disableHotel(@PathVariable Long id) throws ApiRequestExce
      */
 
     @GetMapping("/api/hotel/amenities/{hotelId}")
-    public Set<HotelAmenityDTO> findHotelAmenitiesByHotelId(@PathVariable Long hotelId)throws ApiRequestException{
+    @PreAuthorize("hasAuthority('ADMIN')")
+    public Set<HotelAmenityDTO> findHotelAmenitiesByHotelId(@RequestHeader(name = "Authorization") String token, @PathVariable Long hotelId) throws ApiRequestException {
+
+        HotelDTO hotelOptional = service.getHotelById(hotelId);
+
+        if (Objects.equals(hotelOptional.getOwner(), userService.getUserFromToken(token).getId())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java:229]: Please check or hnadle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/OrderController.java [hunk 10]
```diff
@@ -37,13 +52,27 @@ public OrderDTO addOrder(@RequestBody OrderDTO orderDTO) throws ApiRequestExcept
...
      * @throws ApiRequestException if no orders is saved
      */
-    @GetMapping("/api/orders")
-    public List<OrderDTO> findAllOrders() throws ApiRequestException {
-        return service.getOrders();
+    @GetMapping("/api/orders/client")
+    @PreAuthorize("hasAuthority('CLIENT')")
+    public List<OrderDTO> findAllOrdersClient(@RequestHeader(name = "Authorization") String token) throws ApiRequestException {
+
+        return service.getOrdersClient(userService.getUserFromToken(token).getId());
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/OrderController.java:63]: Please hnadle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/OrderController.java [hunk 11]
```diff
@@ -53,9 +82,18 @@ public List<OrderDTO> findAllOrders() throws ApiRequestException {
...
      */
     @GetMapping("/api/orderId/{id}")
-    public OrderDTO findOrderById(@PathVariable Long id) throws ApiRequestException {
+    public OrderDTO findOrderById(@RequestHeader(name = "Authorization") String token, @PathVariable Long id) throws ApiRequestException {
 
-        return service.getOrderById(id);
+        OrderDTO order = service.getOrderById(id);
+
+        if (Objects.equals(userService.getUserById(order.getClient()), userService.getUserFromToken(token))
+        || Objects.equals(id, hotelService.getHotelById(roomService.getRoomById(order.getRoom()).getHotel()).getOwner())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/OrderController.java:90]: Please check or hnadle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/OrderController.java [hunk 12]
```diff
@@ -66,9 +104,17 @@ public OrderDTO findOrderById(@PathVariable Long id) throws ApiRequestException
      * @throws ApiRequestException if the order that is going to update is not exists
      */
     @PutMapping("/api/order/update")
-    public OrderDTO updateOrder(@RequestBody OrderDTO orderDTO)throws ApiRequestException {
+    @PreAuthorize("hasAuthority('CLIENT')")
+    public OrderDTO updateOrder(@RequestHeader(name = "Authorization") String token, @RequestBody OrderDTO orderDTO) throws ApiRequestException {
+
+        if (Objects.equals(userService.getUserFromToken(token), userService.getUserById(orderDTO.getClient()))) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/OrderController.java:110]: Please check or hnadle NullPointerException and add a TODO comment that this will not be used for the time being, until we decide how we will handle the update of orders

File: src/main/java/com/sphy/hotelmanagementapplication/controller/OrderController.java [hunk 13]
```diff
@@ -79,12 +125,19 @@ public OrderDTO updateOrder(@RequestBody OrderDTO orderDTO)throws ApiRequestExce
      * @throws ApiRequestException if the order does not exist or is already activated
      */
     @PostMapping("/api/order/enable/{id}")
-    ResponseEntity<String> enableOrder(@PathVariable Long id) throws ApiRequestException {
+    @PreAuthorize("hasAuthority('CLIENT')")
+    ResponseEntity<String> enableOrder(@RequestHeader(name = "Authorization") String token, @PathVariable Long id) throws ApiRequestException {
+
+        if (Objects.equals(userService.getUserFromToken(token), userService.getUserById(service.getOrderById(id).getClient()))) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/OrderController.java:131]: Please check or hnadle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/OrderController.java [hunk 14]
```diff
@@ -95,12 +148,19 @@ ResponseEntity<String> enableOrder(@PathVariable Long id) throws ApiRequestExcep
      * @throws ApiRequestException if the order does not exist or is already deactivated
      */
     @PostMapping("/api/order/disable/{id}")
-    ResponseEntity<String> disableRoom(@PathVariable Long id) throws ApiRequestException {
+    @PreAuthorize("hasAuthority('CLIENT')")
+    ResponseEntity<String> disableRoom(@RequestHeader(name = "Authorization") String token, @PathVariable Long id) throws ApiRequestException {
+
+        if (Objects.equals(userService.getUserFromToken(token), userService.getUserById(service.getOrderById(id).getClient()))) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/OrderController.java:154]: Please check or hnadle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java [hunk 15]
```diff
@@ -20,23 +24,37 @@ public class RoomController {
...
      * @return the saved room for confirmation
-     * @throws ApiRequestException if the room's hotel does not exist or if the hotel doesn't given
+     * @throws ApiRequestException if the room's hotel does not exist
      */
     @PostMapping("/api/room/create")
-    public RoomDTO addRoom(@RequestBody RoomDTO roomDTO) throws ApiRequestException {
+    @PreAuthorize("hasAuthority('ADMIN')")
+    public RoomDTO addRoom(@RequestHeader(name = "Authorization") String token, @RequestBody RoomDTO roomDTO) throws ApiRequestException {
+
+        if (Objects.deepEquals(hotelService.getHotelById(roomDTO.getHotel()).getOwner()
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java]: Please check or hnadle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java [hunk 16]
```diff
@@ -20,23 +24,37 @@ public class RoomController {
...
+                , userService.getUserFromToken(token).getId())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java:52]: Please check or hnadle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java [hunk 17]
```diff
@@ -45,19 +63,32 @@ public RoomDTO addRoom(@RequestBody RoomDTO roomDTO) throws ApiRequestException
      * @return the list with the saved rooms
      */
     @PostMapping("/api/rooms/create")
-    public List<RoomDTO> addRooms(@RequestBody List<RoomDTO> roomsDTO) throws ApiRequestException {
+    @PreAuthorize("hasAuthority('ADMIN')")
+
+    public List<RoomDTO> addRooms(@RequestHeader(name = "Authorization") String token, @RequestBody List<RoomDTO> roomsDTO) throws ApiRequestException {
+
+        if (Objects.deepEquals(hotelService.getHotelById(roomsDTO.get(0).getHotel()).getOwner()
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java:72]: Check for all rooms please, and please check or handle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java [hunk 18]
```diff
@@ -45,19 +63,32 @@ public RoomDTO addRoom(@RequestBody RoomDTO roomDTO) throws ApiRequestException
...
     /***
      * counts all the rooms in the database
      * @return the number of rooms that exists in the database
      */
     @GetMapping("/api/rooms/quantity")
-    public int countRooms(){
+    @PreAuthorize("hasAuthority('ADMIN')")
+    public int countRooms(@RequestHeader(name = "Authorization") String token) {
+
+        return service.countRooms(userService.getUserFromToken(token).getId());
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java:92]: Please check or handle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java [hunk 19]
```diff
@@ -66,15 +97,17 @@ public int countRooms(){
...
+    @PreAuthorize("hasAuthority('ADMIN')")
     public ResponseEntity<List<RoomDTO>> findAllRooms(
+            @RequestHeader(name = "Authorization") String token,
             @PathVariable Integer pageNo,
             @PathVariable Integer pageSize,
             @PathVariable String sortBy)
             throws ApiRequestException {
 
-        List<RoomDTO> rooms = service.getRooms(pageNo, pageSize, sortBy);
+        List<RoomDTO> rooms = service.getRooms(pageNo, pageSize, sortBy, userService.getUserFromToken(token).getId());
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java:110]: This seem a better way to handle this endpoint, that providing userId in endpoint, as you did in getHotels. Switch to this flow of actions to getHotels like here?

Also, please check or handle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java [hunk 20]
```diff
@@ -107,9 +140,16 @@ public RoomDTO findRoomByName(@PathVariable String name) throws ApiRequestExcept
      * @throws ApiRequestException if the room that is going to update is not exists
      */
     @PutMapping("/api/room/update")
-    public RoomDTO updateRoom(@RequestBody RoomDTO roomDTO)throws ApiRequestException {
+    @PreAuthorize("hasAuthority('ADMIN')")
+    public RoomDTO updateRoom(@RequestHeader(name = "Authorization") String token, @RequestBody RoomDTO roomDTO) throws ApiRequestException {
+
+        if (Objects.equals(userService.getUserFromToken(token).getId(), hotelService.getHotelById(roomDTO.getHotel()).getOwner())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java:148]: Please check or handle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java [hunk 21]
```diff
@@ -119,14 +159,22 @@ public RoomDTO updateRoom(@RequestBody RoomDTO roomDTO)throws ApiRequestExceptio
      * @return a confirmation message or an error message
      * @throws ApiRequestException if the room does not exist or is already activated
      */
-	@PostMapping("/api/room/enable/{id}")
-	ResponseEntity<String> enableRoom(@PathVariable Long id) throws ApiRequestException {
+    @PostMapping("/api/room/enable/{id}")
+    @PreAuthorize("hasAuthority('ADMIN')")
+    ResponseEntity<String> enableRoom(@RequestHeader(name = "Authorization") String token, @PathVariable Long id) throws ApiRequestException {
+
+        if (Objects.equals(userService.getUserFromToken(token).getId(), hotelService.getHotelById(service.getRoomById(id).getHotel()).getOwner())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java:168]: Please check or handle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java [hunk 22]
```diff
@@ -136,12 +184,19 @@ ResponseEntity<String> enableRoom(@PathVariable Long id) throws ApiRequestExcept
      * @throws ApiRequestException if the room does not exist or is already deactivated
      */
     @PostMapping("/api/room/disable/{id}")
-    ResponseEntity<String> disableRoom(@PathVariable Long id) throws ApiRequestException {
+    @PreAuthorize("hasAuthority('ADMIN')")
+    ResponseEntity<String> disableRoom(@RequestHeader(name = "Authorization") String token, @PathVariable Long id) throws ApiRequestException {
+
+        if (Objects.equals(userService.getUserFromToken(token).getId(), hotelService.getHotelById(service.getRoomById(id).getHotel()).getOwner())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java:192]: Please check or handle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java [hunk 23]
```diff
@@ -152,9 +207,16 @@ ResponseEntity<String> disableRoom(@PathVariable Long id) throws ApiRequestExcep
      */
 
     @GetMapping("/api/room/amenities/{roomId}")
-    public Set<RoomAmenityDTO> findRoomAmenitiesByRoomId(@PathVariable Long roomId) throws ApiRequestException {
+    @PreAuthorize("hasAuthority('ADMIN')")
+    public Set<RoomAmenityDTO> findRoomAmenitiesByRoomId(@RequestHeader(name = "Authorization") String token, @PathVariable Long roomId) throws ApiRequestException {
+
+        if (Objects.equals(userService.getUserFromToken(token).getId(), hotelService.getHotelById(service.getRoomById(roomId).getHotel()).getOwner())) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java:215]: Please check or handle NullPointerException

File: src/main/java/com/sphy/hotelmanagementapplication/repository/OrderRepository.java [hunk 24]
```diff
@@ -7,16 +7,23 @@
...
+import java.util.List;
 
 /***
  * created by gp
  */
 @Repository
 public interface OrderRepository extends CrudRepository<Order,Long> {
 
-    @Query("SELECT count(*) from orders o where o.room=?3 and" +
+    @Query("SELECT count(o) from orders o where o.room=?3 and" +
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/repository/OrderRepository.java]: Please don't use ?  for passing parameters, bacuase there might be a way that this would be vulnerable to sql injection attacks. Use the annotation @Param with named parameters, such as in method findAllAdmin

For reference: https://www.baeldung.com/jpa-query-parameters

File: src/main/java/com/sphy/hotelmanagementapplication/service/RoomService.java [hunk 25]
```diff
@@ -85,45 +94,45 @@ public List<RoomDTO> saveRooms(List<RoomDTO> roomsDTO) throws ApiRequestExceptio
...
-            roomDTOS.add(roomToRoomDTO.converter(roomRepository.findById(room.getId()).get()));
-        }
+
+        rooms.forEach(room -> roomsDTO.add(roomToRoomDTO.converter(room)));
+
         return roomDTOS;
     }
 
     /***
      * counts all the rooms in the database
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/service/RoomService.java:104]: Please write in javadoc what is the parameter id and for what usage.

File: src/main/java/com/sphy/hotelmanagementapplication/service/RoomService.java [hunk 26]
```diff
@@ -85,45 +94,45 @@ public List<RoomDTO> saveRooms(List<RoomDTO> roomsDTO) throws ApiRequestExceptio
...
 
-        Page<Room> pageResult = roomRepository.findAll(paging);
+        Page<Room> pageResult = roomRepository.findAllRoomsByOwner(id, paging);
 
         List<RoomDTO> roomDTOS = new ArrayList<>();
 
-        for (Room room: pageResult.getContent()){
-            roomDTOS.add(roomToRoomDTO.converter(room));
-        }
+        pageResult.getContent().forEach(room -> roomDTOS.add(roomToRoomDTO.converter(room)));
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/service/RoomService.java:130]: I have the notion that this might produce NullPointerException, please add a check if getContent() is not null

File: src/test/java/com/sphy/hotelmanagementapplication/controller/HotelControllerTest.java [hunk 27]
```diff
@@ -284,10 +309,13 @@ void updateHotel() throws Exception {
...
+        when(userService.getUserFromToken(anyString())).thenReturn(admin);
+
 
         // Return
         mockMvc.perform(
                         put("/api/hotel/update")
+                                .header(HttpHeaders.AUTHORIZATION, "Bearer token")
                                 .content(asJsonString(hotelDTO))
                                 .contentType(MediaType.APPLICATION_JSON)
                                 .accept(MediaType.APPLICATION_JSON)
```
Comment (DimK10) [inline src/test/java/com/sphy/hotelmanagementapplication/controller/HotelControllerTest.java:321]: Please check for all fields of hotel

**Review by DimK10 — CHANGES_REQUESTED** [review]
Please read the comments

**Review by DimK10 — APPROVED** [review]
