### PR TITLE
21 create exception handling for the controllers

### LINKED ISSUE #21: Create exception handling for the controllers
Please add exception handling with the format shown in this tutorial 
[exception handling in Spring Boot](https://www.baeldung.com/exception-handling-for-rest-with-spring)
I believe the best one to use is ResponseStatusExceptionResolver, meaning we add exceptions only for status codes.

### PR DESCRIPTION
**Pull request by georgepoul**

### CODE REVIEW

File: src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java [hunk 1]
```diff
@@ -23,36 +18,15 @@ public class HotelController {
...
     }
 
     /***
      * Creates a new hotel
      * @param hotelDTO new hotel to be saved
      * @return the saved hotel for confirmation
-     * @throws Exception
      */
     @PostMapping("/api/hotel/create")
     public HotelDTO addHotel(@RequestBody HotelDTO hotelDTO) throws Exception {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/HotelController.java]: Should we put ApiRequestException instead of Exception?

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java [hunk 2]
```diff
@@ -54,78 +50,78 @@ public List<RoomDTO> addRooms(@RequestBody List<RoomDTO> roomsDTO) throws Except
...
      */
 	@PostMapping("/api/room/enable/{id}")
-	ResponseEntity<String> enableRoom(@PathVariable Long id) {
+	ResponseEntity<String> enableRoom(@PathVariable Long id) throws ApiRequestException {
 
-		if (!service.enableRoom(id)) {
-			return ResponseEntity.badRequest()
-					.body("The id does not exist");
-		} else {
+            service.enableRoom(id);
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java:105]: We need to add if statement as you had it, by throwing manually ApiRequestException

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java [hunk 3]
```diff
@@ -54,78 +50,78 @@ public List<RoomDTO> addRooms(@RequestBody List<RoomDTO> roomsDTO) throws Except
...
      */
     @PostMapping("/api/room/disable/{id}")
-    ResponseEntity<String> disableRoom(@PathVariable Long id) {
+    ResponseEntity<String> disableRoom(@PathVariable Long id) throws ApiRequestException {
 
-        if (!service.disableRoom(id)) {
-            return ResponseEntity.badRequest()
-                    .body("The id does not exist");
-        } else {
+            service.disableRoom(id);
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java:121]: Just as enable method

File: src/main/java/com/sphy/hotelmanagementapplication/service/HotelService.java [hunk 4]
```diff
@@ -137,11 +149,13 @@ public String deleteHotel(Long id){
...
 	 * @return the updated hotel
-	 * @throws NullPointerException
+	 * @throws Exception if the hotel does not exist
 	 */
 	public HotelDTO updateHotel(HotelDTO hotelDTO) throws Exception {
-		Optional<Hotel> hotelOpt = hotelRepository.findById(hotelDTO.getId());
-		if (hotelOpt.isPresent()){
+
+		if (!hotelRepository.existsById(hotelDTO.getId())){
+			throw new ApiRequestException("The hotel with name: " + hotelDTO.getName() + " does not exist to update it");
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/service/HotelService.java]: Maybe add a different kind of exception for such cases?

File: src/main/java/com/sphy/hotelmanagementapplication/service/HotelService.java [hunk 5]
```diff
@@ -151,17 +165,16 @@ public HotelDTO updateHotel(HotelDTO hotelDTO) throws Exception {
...
 	/***
 	 * saves a hotel
 	 * @param hotelDTO hotel to be saved
 	 * @return the saved hotel for confirmation
-	 * @throws Exception
+	 * @throws ApiRequestException if the hotel does not have an Owner or does not have rooms
 	 */
-	public HotelDTO saveHotelDTO(HotelDTO hotelDTO) throws Exception {
-		Hotel hotel = new Hotel(1L);
+	public HotelDTO saveHotelDTO(HotelDTO hotelDTO) throws Exception{
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/service/HotelService.java]: You left it as plain Exception

File: src/main/java/com/sphy/hotelmanagementapplication/service/RoomService.java [hunk 6]
```diff
@@ -91,94 +92,112 @@ public List<RoomDTO> saveRooms(List<RoomDTO> roomsDTO) throws Exception{
...
      */
-    public List<RoomDTO> getRooms() throws Exception {
-		List<Room> rooms = new ArrayList<>();
-        List<RoomDTO> roomsDTO = new ArrayList<>();
-        roomRepository.findAll().forEach(rooms::add);
-        for (Room room : rooms){
-            roomsDTO.add(roomToRoomDTO.converter(room));
+    public List<RoomDTO> getRooms() throws ApiRequestException {
+
+        if (roomRepository.findAll() == null) {
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/service/RoomService.java]: There is no need to add his exception here, because in react, i ll check if the array is empty and i ll show different things in each case

File: src/main/resources/application.properties [hunk 7]
```diff
@@ -1,4 +1,4 @@
-spring.profiles.active=@spring.profiles.active@
+spring.profiles.active=prod
```
Comment (DimK10) [inline src/main/resources/application.properties]: dev

File: src/test/java/com/sphy/hotelmanagementapplication/service/RoomServiceTest.java [hunk 8]
```diff
@@ -192,7 +193,7 @@ void disableRoom() {
 		Room room = new Room();
 		room.setId(1L);
 		room.setName("room");
-		room.setDisabled(true);
```
Comment (DimK10) [inline src/test/java/com/sphy/hotelmanagementapplication/service/RoomServiceTest.java:195]: this should stay false, for actually checking if method that we test it makes the value true

**Review by DimK10 — CHANGES_REQUESTED** [review]

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java (hunk 2 above)
Comment (georgepoul) [reply src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java:105]: i do it on service

File: src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java (hunk 3 above)
Comment (georgepoul) [reply src/main/java/com/sphy/hotelmanagementapplication/controller/RoomController.java:121]: i do it on service

File: src/main/java/com/sphy/hotelmanagementapplication/exception/ApiException.java [hunk 9]
```diff
@@ -0,0 +1,33 @@
...
+public class ApiException {
+
+    private final String message;
+    private final HttpStatus httpStatus;
+    private final ZonedDateTime zonedDateTime;
+
+    public ApiException(String message, HttpStatus httpStatus, ZonedDateTime zonedDateTime) {
+        this.message = message;
+        this.httpStatus = httpStatus;
+        this.zonedDateTime = zonedDateTime;
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/exception/ApiException.java:19]: This can be calculated in cosnstructor as get now in milliseconds, no need for a programmer to add it

File: src/main/java/com/sphy/hotelmanagementapplication/service/HotelService.java [hunk 10]
```diff
@@ -137,11 +148,13 @@ public String deleteHotel(Long id){
...
-	 * @throws NullPointerException
+	 * @throws ApiRequestException if the hotel does not exist
 	 */
-	public HotelDTO updateHotel(HotelDTO hotelDTO) throws Exception {
-		Optional<Hotel> hotelOpt = hotelRepository.findById(hotelDTO.getId());
-		if (hotelOpt.isPresent()){
+	public HotelDTO updateHotel(HotelDTO hotelDTO) throws ApiRequestException {
+
+		if (!hotelRepository.existsById(hotelDTO.getId())){
+			throw new ApiRequestException("The hotel with name: " + hotelDTO.getName() + " does not exist to update it");
```
Comment (DimK10) [inline src/main/java/com/sphy/hotelmanagementapplication/service/HotelService.java]: You check if a hotel exists by id, the error should indicate that the hotel with that id doesnt exist

**Review by DimK10 — CHANGES_REQUESTED** [review]

File: src/main/java/com/sphy/hotelmanagementapplication/exception/ApiException.java (hunk 9 above)
Comment (georgepoul) [reply src/main/java/com/sphy/hotelmanagementapplication/exception/ApiException.java:19]: if we don't added it don't going to sow it on the error

Comment (DimK10) [reply src/main/java/com/sphy/hotelmanagementapplication/exception/ApiException.java:19]: oh ok thanks

**Review by DimK10 — APPROVED** [review]
